FROM nginx:1.27-alpine

RUN rm -f /etc/nginx/conf.d/default.conf

COPY nginx.conf.template /etc/nginx/nginx.conf.template

CMD ["sh", "-c", "envsubst '$$BACKEND_PORT $$FRONTEND_PORT $$NGINX_PORT $$HOST $$DEV' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
